// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.0 (Build Build 156 04/24/2013)
// Created on Fri Dec 07 08:27:36 2018

mips_multi mips_multi_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.clk_rom(clk_rom_sig) ,	// input  clk_rom_sig
	.rst(rst_sig) ,	// input  rst_sig
	.debug(debug_sig) ,	// input [1:0] debug_sig
	.data(data_sig) 	// output [31:0] data_sig
);

